### ISSUE TITLE
Semantic URL for language and algorithm implemented

### ISSUE THREAD

**Issue by irisyuan** [kennyledet/Algorithm-Implementations#405]
Ex. instead of finding the 100 Doors Problem at: http://dry-sea-7022.herokuapp.com/algorithm/1, change to /algorithm/100-doors-problem, then /algorithm/100-doors-problem/java
(for example)

**Comment by kennyledet** [comment]
Extremely busy right now, but I'm planning on implementing this as well as open sourcing the app within the next few weeks.

**Comment by kennyledet** [comment]
Hey, pretty/semantic URLs have been implemented for everything on the site :)
