### ISSUE TITLE
Page on the web app dedicated to the collaborators

### ISSUE THREAD

**Issue by kennyledet** [kennyledet/Algorithm-Implementations#446]
@jcla1 , @patrickyevsukov , @dalleng 

Hey, you guys have been extremely helpful and dedicated to the repo! I just want to take the time out from my schedule to thank each one of you. You're hugely contributing factors to why this repo has been successful, in addition to all the algorithm contributors.

Before eventually open-sourcing the web app (still kinda busy with work and iOS app projects, and I want the Flask codebase to be perfectly clean and ready for open source), I plan on adding a new page to it dedicated to the contributors (links to blogs/resumes, etc.).

Is this cool with you all? What would you like to see on this page?

Best regards,
Kendrick L.

**Comment by Yonaba** [comment]
Hey, I admit I didn't made loads of contributions, but I feel like I've been forgotten here :8ball: 
Lol, joking.
Sounds like a great idea anyway! :+1:

**Comment by kennyledet** [comment]
Ah crap man, my bad, I must have forgotten that I made you a collaborator! Github also screwed up by only showing those 3, was going off that. Will add you on the webpage as well.

**Comment by dalleng** [comment]
It sound like a good idea! BTW @Yonaba definitely deserves a spot. I think links to github, LinkedIn, StackOverflow, etc. would be nice. It's always good to have some online presence to show to prospective employers.

**Comment by patrickyevsukov** [comment]
Thanks for the kind words! This is cool with me.

All I have online now besides my GitHub is:

My Twitter: https://twitter.com/patrickyevsukov

And my website: https://patrick.yevsukov.com

**Comment by patrickyevsukov** [comment]
Also, I'm definitely in favor of adding @Yonaba as a collaborator. He's contributed about half of the repo. lol 

I believe this was last discussed in #132. Perhaps that's why only the three users you mentioned were shown.

As an aside: I'm not a big fan of GitHub's term collaborator. I think it has the wrong connotation; after all, anyone who has contributed is a "collaborator." Perhaps a "maintainers" page would be better to describe those of us with commit access.

**Comment by kennyledet** [comment]
Ah yes, I remember now, I remember definitely realizing that Yonaba deserved a spot, but he asked me to ask him later. @Yonaba  , would you like one now?

@patrickyevsukov I totally agree. I also dislike the term and was thinking about using "Managers", but "Maintainers" is a much better word. Will most likely use that.

Gonna go ahead and hack on the page this weekend, after I've gotten back to campus and settled in. Should be up the same day.

Thanks for the quick responses everyone!

Best regards,
Kendrick L.

**Comment by Yonaba** [comment]
If I would like what ? Be a collaborator ? Hell yes!
Thanks in advance. Sorry if I hadn't contributed in a while, I am just missing free time these days. I'll be pushing some new implementations very soon. ;)

**Comment by Yonaba** [comment]
If I would like what ? Be a collaborator ? Hell yes!
Thanks in advance. Sorry if I hadn't contributed in a while, I am just missing free time these days. I'll be pushing some new implementations very soon. ;)

**Comment by kennyledet** [comment]
Alright, making you one now. And no worries bro, all of your contributions will always be appreciated, no matter how busy you are. You're *still* the top contributor and definitely one of the biggest driving forces behind this project.

**Comment by Yonaba** [comment]
Thanks for the kind words, all of you. Very much appreciated.

**Comment by kennyledet** [comment]
Np man, it's very much deserved and long overdue.

**Comment by kennyledet** [comment]
Hey guys, this should be finished by this Saturday, getting settled back into school after break has taken more time than I expected.

**Comment by kennyledet** [comment]
Hey guys, I'm working on it right now, hopefully I'll have it up tonight. I'm coding it up along with some general fixes and improvements here and there around the app.

**Comment by kennyledet** [comment]
For now it's just static HTML as a placeholder to get everyone's feedback and see what we really want. But I plan on implementing a special admin panel for you guys to be able to change the content dynamically.

**Comment by kennyledet** [comment]
@Yonaba @patrickyevsukov @dalleng @jcla1 

Hey, here's just a static, rudimentary example of how the cards would be laid out, theoretically.

https://dry-sea-7022.herokuapp.com/maintainers

I typed Yonaba's card statically, but I plan on implementing the appropriate database tables and backend administration panels for yal to configure your cards how you like.


Best regards,
Kendrick L.

**Comment by dalleng** [comment]
Very nice! Thanks for doing this Kenny!

**Comment by kennyledet** [comment]
Yal are most welcome. This is just the beginning, I have a bunch of great plans for the site and now that I have more free time I'll be able to see them come to fruition.

—

**Comment by patrickyevsukov** [comment]
It looks great! Thanks!

**Comment by jcla1** [comment]
Great page! Thanks!

**Comment by kennyledet** [comment]
Alright, so since yal are satisified with it then I will go ahead and start development on the backend stuff. Thanks for the feedback, have a good 1

**Comment by kennyledet** [comment]
Hey, sorry for the delay, been real busy with work and school. Everything should be wrapped up by next week.

**Comment by patrickyevsukov** [comment]
Great news! Also, I recently had a chance to work with Python and Flask for the first time; I'm quite interested to take a look at the code for this repo's web app once it's up.

**Comment by kennyledet** [comment]
Hey everyone, we are really close now. Just want to finish up the base implementation of the automated database updates feature (pulling in from the repo periodically to keep the algorithm list fresh, using Celery as the asynchronous task queue with Redis as the store).

@patrickyevsukov Sorry I missed your message. I was relying on the email updates to keep me in the loop, but seeing as how I'm always missing things I'm now going to just visit the repo daily, as my inbox is extremely cluttered.

Nice to hear you have picked up Flask. Among all the latest weekly JS frameworks popping up, it's still my favorite framework to this day, hands-down. How are you liking it and Python? Awesome, right?

**Comment by patrickyevsukov** [comment]
Python is exceptional. It's remarkably expressive and by far the most concise language I've ever used. I wish I had thought to try it out a while ago. Flask is great too. Until I learned Python, my experience with  web app frameworks centered around PHP and Laravel. Laravel is excellent; however, I now would personally prefer to use Python over PHP. I'm glad you chose Flask for this repo's web app.

**Comment by kennyledet** [comment]
@patrickyevsukov Missed your reply, but I played around with Laravel and it's pretty great for a PHP framework. I truly believe it gave the PHP crowd that needed boost for the frameworks to really start stepping their game up.

**Comment by patrickyevsukov** [comment]
Very true. Before I discovered Laravel, I used vanilla PHP to write a couple of small web apps. It was not a pleasurable experience. Laravel is a breath of fresh air.

**Comment by kennyledet** [comment]
Ah yes, the old vanilla PHP days. Man. That was back when I was first learning web development, so it was relatively fun, built the usual practice/learning apps in raw PHP. Enjoyable because it was so novel, but this was before I knew what the good practices were. It was bittersweet switching to Python and Django, then ultimately settling on Flask as my goto framework.

**Comment by kennyledet** [comment]
Alright, this is going to be integrated with the new Github user integration I'm working on, so I'm gonna close this and start a new one for that within a few days.
