### ISSUE TITLE
Incorrect Algorithms

### ISSUE THREAD

**Issue by rohanp** [kennyledet/Algorithm-Implementations#462]
Both of these produce incorrect output.

https://github.com/kennyledet/Algorithm-Implementations/blob/master/99_Bottles_Problem/Python/jiang42/99bottles.py

https://github.com/kennyledet/Algorithm-Implementations/blob/master/99_Bottles_Problem/Python/tylerferraro/99bottles.py

**Comment by kennyledet** [comment]
Thanks for reaching out.

I am working on a solution that will ensure better validation for submissions. This will go along with the new test requirement.

Best,
Kendrick

**Comment by patrickyevsukov** [comment]
Thanks for bringing this to us, @rohanp

**Comment by rohanp** [comment]
No Problem.

**Comment by patrickyevsukov** [comment]
@rohanp Please note yours is incorrect as well. See line 198 in your test file.

I have cloned the repo and am correcting them now.

**Comment by rohanp** [comment]
Oops.

On Mon, Jul 6, 2015 at 9:33 AM, Patrick Yevsukov <notifications@github.com>
wrote:

> @rohanp <https://github.com/rohanp> Please note yours is incorrect as
> well. See line 198 in your test file.
>
> I have cloned the repo and am correcting them now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kennyledet/Algorithm-Implementations/issues/462#issuecomment-118855422>
> .
>



-- 
From,
Rohan Pandit

**Comment by patrickyevsukov** [comment]
No worries, rohanp . Thanks for the fix!

**Comment by patrickyevsukov** [comment]
I've corrected all of the erroneous 99 bottles Python implementations, and added test output.

**Comment by kennyledet** [comment]
Thank you Patrick, that was awesome of you. I appreciate it very much!
