### ISSUE TITLE
Errors in python implementations for binary_search

### ISSUE THREAD

**Issue by dalleng** [kennyledet/Algorithm-Implementations#469]
I added unit tests for python implementations of binary search and noticed that @jiang42 and @rohanp implementations do not pass all test cases. I think that both users should submit pull requests fixing the bugs. 

How should we handle these cases @kennyledet @patrickyevsukov @jcla1 @Yonaba  ? Keep the files and wait till they're fix, removing and waiting for the committer to resubmit?

**Comment by jiang42** [comment]
please provide your unit tests.

**Comment by jiang42** [comment]
Fix it, please verify.

**Comment by dalleng** [comment]
I just merged @jiang42's pull request and it test are passing. Now we just need to wait for @rohanp to fix his code.

**Comment by patrickyevsukov** [comment]
Thanks for the fix, @jiang42 , and thanks for catching these @dalleng !

> "How should we handle these cases ... Keep the files and wait till they're fix, removing and waiting for the committer to resubmit?"

My thoughts on this: Anytime one of us identifies errors in a legacy algorithm submission, we should open an issue referencing the submission and politely request a fix from the submission's author, label the issue as a bug, and wait for a fix.
